[package]
name = "coze"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.25.0"
env_logger = "0.11"
log = "0.4"
serde = { version = "1", features = ["derive"] }

[dependencies.eframe]
version = "0.25.0"
default-features = false
features = ["default_fonts", "glow", "persistence"]
